backend:
  name: github
  repo: majasoroka/feminism
  branch: main
  base_url: https://feminism-175.pages.dev
  auth_endpoint: /api/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "index"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
